{% set python_min = python_min|default("3.9") %}
{% set name = "sphinxcontrib-confluencebuilder" %}
{% set version = "2.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sphinxcontrib_confluencebuilder-{{ version }}.tar.gz
  sha256: 3497e8106679044d547c7b034ca16fb3e8513fae7c2f270efa2ceec6fd4599a4

build:
  entry_points:
    - sphinx-build-confluence = sphinxcontrib.confluencebuilder.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.7
    - pip
  run:
    - python >={{ python_min }}
    - requests >=2.25.0
    - sphinx >=7.2

test:
  imports:
    - sphinxcontrib
    - sphinxcontrib.confluencebuilder
  commands:
    - pip check
    - sphinx-build-confluence --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/sphinx-contrib/confluencebuilder
  summary: Sphinx extension to build Atlassian Confluence Storage Markup
  dev_url: https://github.com/sphinx-contrib/confluencebuilder
  license: BSD-2-Clause
  license_file:
    - LICENSE-3RD-PARTY
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/sphinx
    - maresb
