{% set name = "sphinxcontrib-confluencebuilder" %}
{% set version = "2.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinxcontrib_confluencebuilder-{{ version }}.tar.gz
  sha256: da517c892f1ceca5c37574f622e029167c74838b325a620fd72db95b90e49090

build:
  entry_points:
    - sphinx-build-confluence = sphinxcontrib.confluencebuilder.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - flit-core >=3.7
    - pip
  run:
    - python >=3.9
    - requests >=2.25.0
    - sphinx >=7.2

test:
  imports:
    - sphinxcontrib
    - sphinxcontrib.confluencebuilder
  commands:
    - pip check
    - sphinx-build-confluence --help
  requires:
    - pip

about:
  home: https://github.com/sphinx-contrib/confluencebuilder
  summary: Sphinx extension to build Atlassian Confluence Storage Markup
  dev_url: https://github.com/sphinx-contrib/confluencebuilder
  license: BSD-2-Clause
  license_file:
    - LICENSE-3RD-PARTY
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/sphinx
    - maresb
