{% set name = "sphinxcontrib-confluencebuilder" %}
{% set version = "1.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinxcontrib-confluencebuilder-{{ version }}.tar.gz
  sha256: 6a3fbcfd9396a53d7305d0938ade99a3f5e19f3162b0b93faeb83997ab0f9a4c

build:
  number: 0
  noarch: python
  entry_points:
    - sphinx-build-confluence = sphinxcontrib.confluencebuilder.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    # https://github.com/sphinx-contrib/confluencebuilder/blob/v{{ version }}/setup.py
    - python >=3.5
    - requests >=2.14.0
    - sphinx >=1.8

test:
  imports:
    - sphinxcontrib
    - sphinxcontrib.confluencebuilder
  commands:
    - pip check
    - sphinx-build-confluence --help
  requires:
    - pip

about:
  home: https://github.com/sphinx-contrib/confluencebuilder
  summary: Sphinx extension to output Atlassian Confluence Storage Markup documents and publish to Confluence instances.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
