{% set name = "sphinxcontrib-confluencebuilder" %}
{% set version = "1.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinxcontrib-confluencebuilder-{{ version }}.tar.gz
  sha256: bbeb23863ff67eef1f2c645bdb3827348fb2ef02085184cc26145e92b76d31e5

build:
  number: 0
  noarch: python
  entry_points:
    - sphinx-build-confluence = sphinxcontrib.confluencebuilder.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - requests >=2.14.0
    - sphinx >=1.8

test:
  imports:
    - sphinxcontrib
    - sphinxcontrib.confluencebuilder
  commands:
    - pip check
    - sphinx-build-confluence --help
  requires:
    - pip

about:
  home: https://github.com/sphinx-contrib/confluencebuilder
  summary: Sphinx extension to output Atlassian Confluence Storage Markup documents and publish to Confluence instances.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
