{% set name = "sphinxcontrib-confluencebuilder" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: eca6def339e3fb1722331d365c7663700955a90faad0f13fa731426d38a2524a

build:
  number: 0
  noarch: python
  entry_points:
    - sphinx-build-confluence = sphinxcontrib.confluencebuilder.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    # https://github.com/sphinx-contrib/confluencebuilder/blob/v{{ version }}/setup.py
    - python >=3.7
    - requests >=2.14.0
    - sphinx >=4.3

test:
  imports:
    - sphinxcontrib
    - sphinxcontrib.confluencebuilder
  commands:
    - pip check
    - sphinx-build-confluence --help
  requires:
    - pip

about:
  home: https://github.com/sphinx-contrib/confluencebuilder
  summary: Sphinx extension to output Atlassian Confluence Storage Markup documents and publish to Confluence instances.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
